language: java
jdk:
 - oraclejdk8
# - openjdk8

os:
 - linux
 
env:
  global:
   - JAVA_OPTS="-enableassertions -Xmx1g"
   - _JAVA_OPTIONS="-enableassertions -Xmx1g"

script: cd trunk/source/BA_MavenParentUltimate && mvn clean install -Pcoverage

branches:
  only:
    - dev
    - stable

notifications:
  irc:
    channels:
      - "irc.quakenet.org#sopra-crew"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true	
  # do not annoy people	
  email: 
  - dietsch@informatik.uni-freiburg.de

sudo: false